---
title: "Performance analysis of the pipeline for the spxdb database"
output: html_notebook
---


```{r setup}
library(targets)
library(dplyr)
library(ggplot2)

knitr::opts_knit$set(root.dir = normalizePath("..")) 
```

# Performance of tracing 

```{r durations}
traced_durations <- tar_meta(fields = "seconds", complete_only = TRUE, names = starts_with("traced_results")) %>% filter(name %in% names(tar_read(traced_results)))
normal_durations <- tar_meta(fields = "seconds", complete_only = TRUE, names = starts_with("run_results2")) %>% filter(name %in% tar_branches(run_results2, map(individual_files))$run_results2)
```

```{r slowdown}
slowdown <- tibble(slow = traced_durations$seconds / normal_durations$seconds)
```

The average of the slowdowns is `r mean(slowdown$slow)` and the median is `r median(slowdown$slow)`, with a standard deviation of `r sd(slowdown$slow)`.

```{r slowdown-plot}
slowdown %>% ggplot(aes(x = slow)) + geom_histogram(bins = 100)
```

What are the outliers?

```{r slowdown-outliers}
outliers <- slowdown %>% filter(slow > 20)
```

