---
title: "Database figures"
author: "Pierre Donat-Bouillud"
date: "12/6/2021"
output: html_document
---

```{r setup, include=FALSE}
library(targets)
library(dplyr)
library(ggplot2)
library(sxpdb)

knitr::opts_knit$set(root.dir = normalizePath(".")) #...

here::i_am("notebooks/database.Rmd")
library(here)
```

## Loading the database

```{r load-db}
db <- open_db(here("data", "sxpdb", "cran_db"))
```

The database has `r size_db(db)` unique values.

```{r meta_info}
meta <- view_meta_db(db) %>% as_tibble() %>% 
  mutate(id = row_number() - 1)
```

```{r origin_infos}
origins <- bind_rows(view_origins_db(db), .id = "id") %>% as_tibble() %>% mutate(id = strtoi(id) - 1)
```

We can now close the database, as we have now all the metadata we wanted as R values.
```{r closing}
#close_db(db)
```

## Types in the database

```{r types}
meta %>% count(type, sort = TRUE) %>% mutate(pc = n / sum(n) * 100, cpc = cumsum(pc)) %>% mutate(s_type = purrr::map_chr(type, string_sexp_type), .before = type)
```

## Sizes

```{r sizes}
meta %>% group_by(type) %>% summarize(size = sum(size)) %>% arrange(desc(size)) %>% mutate(pc = size / sum(size) * 100, cpc = cumsum(pc)) %>% mutate( M_size = size / 1024 / 1024) %>% mutate(s_type = purrr::map_chr(type, string_sexp_type), .before = type)
```


### Big lists

```{r bug_lists}
meta %>% filter(type == 19) %>% arrange(desc(size)) %>% mutate( M_size = size / 1024 / 1024) %>% mutate(s_type = purrr::map_chr(type, string_sexp_type), .before = type)
```

## Frequency of values

```{r freq_values}
meta %>% rename(n_values = n) %>% count(type, wt = n_values, sort = TRUE) %>% mutate(pc = n / sum(n) * 100, cpc = cumsum(pc)) %>% mutate(s_type = purrr::map_chr(type, string_sexp_type), .before = type)
```

## Length of values

```{r length_values}
meta %>% group_by(type) %>% summarize(med_length = median(length), avg_length = mean(length), sd_length = sd(length)) %>% arrange(desc(med_length)) %>% mutate(s_type = purrr::map_chr(type, string_sexp_type), .before = type)
```

```{r length_histogram}
lengths_dist <- meta %>% count(length, sort = TRUE)
lengths_dist %>% filter(length > 0, length < 10^7) %>% ggplot(aes(x = length, y = n)) + geom_col(width = 1, color = "black") + scale_y_log10() +  scale_x_continuous(breaks = scales::log_breaks(n = 10)) + theme(axis.text = element_text(size = 12))
```


## Number of attributes

```{r nb_attributes}
meta %>% count(n_attributes, sort = TRUE)

```

```{r attr_per_types}
meta %>% group_by(type) %>% summarize(med_attr = median(n_attributes), avg_attr = mean(n_attributes), sd_attr = sd(n_attributes)) %>% arrange(desc(med_attr)) %>% mutate(s_type = purrr::map_chr(type, string_sexp_type), .before = type)
```

## Real vectors

```{r real_vectors}
meta %>% filter(type == 14) %>% count(length, sort = TRUE) %>% mutate(pc = n / sum(n) * 100, cpc = cumsum(pc))
```

```{r real_vector_length_plot}
meta %>% filter(type == 14) %>% ggplot(aes(x = length)) + geom_bar()
```

